### ISSUE TITLE
Authorization header should be customizable

### ISSUE THREAD

**Issue by sibeliusseraphini** [glazedio/frisbee#8]
Right now it is only Basic <token> - https://github.com/niftylettuce/frisbee/blob/master/src%2Ffrisbee.js#L203

it should handle JWT <token> and so on

**Comment by niftylettuce** [comment]
done, see `frisbee@1.0.0` @sibeliusseraphini

**Comment by casoetan** [comment]
HI @niftylettuce How do I get it to work with JWT.

tried
```js
api.auth('jwt token')
```

On inspecting the request, the token dispatched is wrong. This causes a JWT <code>Wrong number of segments</code>

**Comment by niftylettuce** [comment]
I believe JSON Web Tokens have different headers than BasicAuth.  Perhaps you could add `api.jwt` method and send a pull request @casoetan?  I think some people even pass it in the body of the request as `token` field.  You could just do `await api.post('/authenticate', { body: { token: 'my jwt' } });`

**Comment by casoetan** [comment]
@niftylettuce pull request sent.

**Comment by niftylettuce** [comment]
Published v1.1.1 to npm.  `npm i --save frisbee@1.1.1` @casoetan 

Thank you for your contributions!  Would you like to be a collaborator here?

**Comment by casoetan** [comment]
That would be fine. What's the road map?

**Comment by niftylettuce** [comment]
@casoetan Can you join me in Slack?  http://slack.crocodilejs.com  Might be easier to chat there.  I wanted to rewrite this package a bit -- and preserve the original `response` (or `res`) object rather due to issues in Chrome #11.  Basically I wanted to get this working on all browsers too with automated tests.  Have you experience there?  Thanks!

**Comment by casoetan** [comment]
@niftylettuce I'm on you slack channel now.

Best, \Charles
Sent using CloudMagic [https://cloudmagic.com/k/d/mailapp?ct=pi&cv=6.3.16&pv=8.3]
On Tue, Aug 2, 2016 at 06:01, niftylettuce <notifications@github.com> wrote:
@casoetan [https://github.com/casoetan] Can you join me in Slack? http://slack.crocodilejs.com [http://slack.crocodilejs.com] Might be easier to chat there. I wanted to rewrite this package a bit -- and preserve the original response (or res ) object rather due to issues in Chrome #11 [https://github.com/crocodilejs/frisbee/issues/11] . Basically I wanted to get this working on all browsers too with automated tests. Have you experience there? Thanks!
